added debugging for update-cors.ps1

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -125,6 +125,14 @@ jobs:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+          enable-AzPSSession: true
+
+      - name: Get Azure Context
+        uses: azure/powershell@v1
+        with:
+          azPSVersion: "latest"
+          inlineScript: |
+            Get-AzContext 
   
       - name: Release function code
         uses: Azure/functions-action@v1
@@ -149,17 +157,6 @@ jobs:
               -CosmosDbDatabaseName "${{ needs.deploy.outputs.cosmosDbDatabaseName }}" `
               -CosmosDbContainerName "${{ needs.deploy.outputs.cosmosDbContainerName }}" `
               -CosmosDbContainerPartitionKey "${{ needs.deploy.outputs.cosmosDbContainerPartitionKey }}"
-      
-      - name: Update CORS
-        uses: azure/powershell@v1
-        with:
-          azPSVersion: "latest"
-          inlineScript: |
-            ./scripts/update-cors.ps1 `
-              -ResourceGroupName "${{ inputs.resourceGroupName }}" `
-              -FunctionAppName "${{ needs.deploy.outputs.functionAppName }}" `
-              -AllowedOrigins "${{ needs.deploy.outputs.swaUrl }}" `
-              -SubscriptionId "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
               
       - name: Replace Placeholders in HTML
         uses: azure/powershell@v1
@@ -179,6 +176,26 @@ jobs:
               -ResourceGroupName "${{ inputs.resourceGroupName }}" `
               -FunctionAppName "${{ needs.deploy.outputs.functionAppName }}" `
               -CosmosDbAccountName "${{ needs.deploy.outputs.cosmosDbAccountName }}"
+
+      - name: Azure CLI Debugging
+        run: |
+          echo "Checking Function App existence using Azure CLI"
+          az functionapp show --name ${{ needs.deploy.outputs.functionAppName }} --resource-group ${{ inputs.resourceGroupName }} || echo "Function App not found using Azure CLI"
+      
+      - name: Debug Subscription ID
+        run: |
+          echo "Subscription ID: ${SECRETS_AZURE_SUBSCRIPTION_ID:0:5}"
+
+      - name: Update CORS
+        uses: azure/powershell@v1
+        with:
+          azPSVersion: "latest"
+          inlineScript: |
+            ./scripts/update-cors.ps1 `
+              -ResourceGroupName "${{ inputs.resourceGroupName }}" `
+              -FunctionAppName "${{ needs.deploy.outputs.functionAppName }}" `
+              -AllowedOrigins "${{ needs.deploy.outputs.swaUrl }}" `
+              -SubscriptionId "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
 
   push:
     needs: [ deploy, release-and-config ]
